import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: "doc",
      id: "index",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Resources",
      items: [{ type: "autogenerated", dirName: "resources" }],
    },
    {
      type: "category",
      label: "Building and Deploying",
      items: [{ type: "autogenerated", dirName: "building-and-deploying" }],
    },
    {
      type: "category",
      label: "Monitoring",
      items: [{ type: "autogenerated", dirName: "monitoring" }],
    },
    {
      type: "category",
      label: "Advanced",
      items: [{ type: "autogenerated", dirName: "advanced" }],
    },
    {
      type: "doc",
      id: "security",
    },
    {
      type: "doc",
      id: "glossary",
    },
  ],
  guidesSidebar: [
    {
      type: "doc",
      id: "guides-and-samples/index",
    },
    {
      type: "category",
      label: "Software",
      items: [
        { type: "autogenerated", dirName: "guides-and-samples/software" },
      ],
    },
    {
      type: "category",
      label: "Languages",
      items: [
        {
          type: "category",
          label: "Javascript / Typescript",
          items: [
            {
              type: "autogenerated",
              dirName: "guides-and-samples/languages/javascript",
            },
          ],
        },
        // {
        //   type: "category",
        //   label: "Python",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "guides-and-samples/languages/python",
        //     },
        //   ],
        // },
        // {
        //   type: "category",
        //   label: "Java",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "guides-and-samples/languages/java",
        //     },
        //   ],
        // },
        // {
        //   type: "category",
        //   label: "Ruby",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "guides-and-samples/languages/ruby",
        //     },
        //   ],
        // },
        // {
        //   type: "category",
        //   label: "Rust",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "guides-and-samples/languages/rust",
        //     },
        //   ],
        // },
        // {
        //   type: "category",
        //   label: "Go",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "guides-and-samples/languages/go",
        //     },
        //   ],
        // },
        // {
        //   type: "category",
        //   label: "PHP",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "guides-and-samples/languages/php",
        //     },
        //   ],
        // },
      ],
    },
  ],
  sdksSidebar: [
    {
      type: "doc",
      id: "sdks/index",
    },
  ],
};

export default sidebars;
