# IMPORTANT: This is built with the context of the root folder, not the docker folder!
FROM node:22.18.0-alpine3.22 AS build

WORKDIR /build

ARG DOCS_URL
ARG TYPESENSE_FQDN
ARG TYPESENSE_API_KEY

ENV DOCS_URL=$DOCS_URL \
    TYPESENSE_FQDN=$TYPESENSE_FQDN \
    TYPESENSE_API_KEY=$TYPESENSE_API_KEY

COPY . .

RUN npm install --frozen-lockfile

RUN npm run build:prod

# TODO: Implement brotli compression
# Compress all build files with gzip
# But keep original files
RUN cd /build/build && find . -type f -exec gzip -9 -k \{\} \;

FROM nginx:1.29.1-alpine3.22

COPY --from=build /build/build /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf