# IMPORTANT: This is built with the context of the root folder, not the docker folder!
FROM node:22.18.0-alpine3.22 AS build

WORKDIR /build

COPY . .

RUN npm install --frozen-lockfile

RUN npm run build:prod

# Compress all build files with gzip
# But keep original files
# TODO: Implement brotli compression
RUN cd /build/build && find . -type f -exec gzip -9 -k \{\} \;

FROM nginx:1.29.1-alpine3.22

COPY --from=build /build/build /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf