on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  remove:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Remove Preview Deployment"
        run: |
          ./remove.sh
